### ISSUE TITLE
Include FM_service_contour_current.txt

### ISSUE THREAD

**Issue by kanet77** [jradavenport/fm_map#1]
The code references a file FM_service_contour_current.txt that is not included in this repo. I think it makes sense to include it.

Is that information publicly available somewhere?

**Comment by jradavenport** [comment]
Ahh yes! Sorry. That file is large (200mb), so didn't want to host on GitHub

You can get the latest version from the [FCC directly](https://www.fcc.gov/media/radio/fm-service-contour-data-points)
